package io.github.trulyfree.modular8.general;

/**
 * Sortable interface. All groups or lists which may have sorting qualities
 * should implement this so that external calls may sort the object's contents.
 * 
 * @author vtcakavsmoace
 *
 */
public interface Sortable {

	/**
	 * Method to be called in order to sort the object's contents. Note that no
	 * errors should be generated by this method. They should all be handled
	 * properly and, should the method fail due to error, the method return
	 * false.
	 * 
	 * @return success A boolean representing the success of the sort operation.
	 */
	public boolean sort();

}
